[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://api.netlify.com/:splat"
  status = 200
  force = true